@server_HostAddress = http://localhost:5053

GET {{server_HostAddress}}/weatherforecast/
Accept: application/json

###

### Register a new user
POST http://localhost:5053/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "password123"
}

### Login
POST http://localhost:5053/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}